The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [1]:
import numpy as np

ExampleGet your own Python Server
Make a copy, change the original array, and display both arrays:

In [2]:
x=np.array([1,2,3,4,5])
x1=x.copy()
x[0]=42
print(x)
print(x1)


[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
y=np.array([10,20,30,40,50])
y1=y.copy()
y[3]=80
print(y)
print(y1)


[10 20 30 80 50]
[10 20 30 40 50]


In [6]:
z=np.array([20,40,80,90])
z1=z.copy()
z[2]=100
print(z)
print(z1)

[ 20  40 100  90]
[20 40 80 90]


Example
Make a view, change the view, and display both arrays:

In [7]:
x=np.array([10,20,30,40,50])
x1=x.view()
x[2]=90
print(x)
print(x1)

[10 20 90 40 50]
[10 20 90 40 50]


In [8]:
x=np.array([1,2,3,4,5])
x1=x.view()
x[1]=10
print(x)
print(x1)

[ 1 10  3  4  5]
[ 1 10  3  4  5]
